/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CodeRouteImport } from './routes/$code'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FundRahulRouteImport } from './routes/fund-rahul'
import { Route as SiteMapRouteImport } from './routes/site-map'
import { Route as HeenaIndexRouteImport } from './routes/heena/index'
import { Route as LegalCancellationPolicyRouteImport } from './routes/legal/cancellation-policy'
import { Route as LegalDisclaimerRouteImport } from './routes/legal/disclaimer'
import { Route as LegalPrivacyPolicyRouteImport } from './routes/legal/privacy-policy'
import { Route as LegalRefundPolicyRouteImport } from './routes/legal/refund-policy'
import { Route as LegalTermsAndConditionsRouteImport } from './routes/legal/terms-and-conditions'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio/index'
import { Route as PortfolioCategoryRouteImport } from './routes/portfolio/$category'
import { Route as PovIndexRouteImport } from './routes/pov/index'
import { Route as PovCategoryRouteImport } from './routes/pov/$category'
import { Route as ReferralsIndexRouteImport } from './routes/referrals/index'
import { Route as ReferralsCategoryRouteImport } from './routes/referrals/$category'
import { Route as ApiPublicAnalyticsInsightsRouteImport } from './routes/api/public/analytics-insights'
import { Route as ApiPublicIndexSiteContentRouteImport } from './routes/api/public/index-site-content'
import { Route as ApiPublicLogAuthEventRouteImport } from './routes/api/public/log-auth-event'
import { Route as ApiPublicRamoguChatRouteImport } from './routes/api/public/ramogu-chat'
import { Route as ApiPublicRazorpayCreateOrderRouteImport } from './routes/api/public/razorpay-create-order'
import { Route as ApiPublicRazorpayVerifyPaymentRouteImport } from './routes/api/public/razorpay-verify-payment'
import { Route as ApiPublicRazorpayWebhookRouteImport } from './routes/api/public/razorpay-webhook'
import { Route as ApiPublicSmartIndexSiteRouteImport } from './routes/api/public/smart-index-site'
import { Route as ApiPublicTrackAnalyticsRouteImport } from './routes/api/public/track-analytics'
import { Route as ApiPublicTrackUrlClickRouteImport } from './routes/api/public/track-url-click'
import { Route as ApiPublicTranscribeAudioRouteImport } from './routes/api/public/transcribe-audio'
import { Route as ApiPublicWorkspaceAiChatRouteImport } from './routes/api/public/workspace-ai-chat'
import { Route as HeenaAdminIndexRouteImport } from './routes/heena/admin.index'
import { Route as HeenaAdminSplatRouteImport } from './routes/heena/admin.$'
import { Route as ApiPublicFileSplatRouteImport } from './routes/api/public/file/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeRoute = CodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FundRahulRoute = FundRahulRouteImport.update({
  id: '/fund-rahul',
  path: '/fund-rahul',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteMapRoute = SiteMapRouteImport.update({
  id: '/site-map',
  path: '/site-map',
  getParentRoute: () => rootRouteImport,
} as any)
const HeenaIndexRoute = HeenaIndexRouteImport.update({
  id: '/heena/',
  path: '/heena/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCancellationPolicyRoute = LegalCancellationPolicyRouteImport.update({
  id: '/legal/cancellation-policy',
  path: '/legal/cancellation-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalDisclaimerRoute = LegalDisclaimerRouteImport.update({
  id: '/legal/disclaimer',
  path: '/legal/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyPolicyRoute = LegalPrivacyPolicyRouteImport.update({
  id: '/legal/privacy-policy',
  path: '/legal/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRefundPolicyRoute = LegalRefundPolicyRouteImport.update({
  id: '/legal/refund-policy',
  path: '/legal/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsAndConditionsRoute = LegalTermsAndConditionsRouteImport.update({
  id: '/legal/terms-and-conditions',
  path: '/legal/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioCategoryRoute = PortfolioCategoryRouteImport.update({
  id: '/portfolio/$category',
  path: '/portfolio/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const PovIndexRoute = PovIndexRouteImport.update({
  id: '/pov/',
  path: '/pov/',
  getParentRoute: () => rootRouteImport,
} as any)
const PovCategoryRoute = PovCategoryRouteImport.update({
  id: '/pov/$category',
  path: '/pov/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsIndexRoute = ReferralsIndexRouteImport.update({
  id: '/referrals/',
  path: '/referrals/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsCategoryRoute = ReferralsCategoryRouteImport.update({
  id: '/referrals/$category',
  path: '/referrals/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAnalyticsInsightsRoute =
  ApiPublicAnalyticsInsightsRouteImport.update({
    id: '/api/public/analytics-insights',
    path: '/api/public/analytics-insights',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicIndexSiteContentRoute =
  ApiPublicIndexSiteContentRouteImport.update({
    id: '/api/public/index-site-content',
    path: '/api/public/index-site-content',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLogAuthEventRoute = ApiPublicLogAuthEventRouteImport.update({
  id: '/api/public/log-auth-event',
  path: '/api/public/log-auth-event',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRamoguChatRoute = ApiPublicRamoguChatRouteImport.update({
  id: '/api/public/ramogu-chat',
  path: '/api/public/ramogu-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRazorpayCreateOrderRoute =
  ApiPublicRazorpayCreateOrderRouteImport.update({
    id: '/api/public/razorpay-create-order',
    path: '/api/public/razorpay-create-order',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRazorpayVerifyPaymentRoute =
  ApiPublicRazorpayVerifyPaymentRouteImport.update({
    id: '/api/public/razorpay-verify-payment',
    path: '/api/public/razorpay-verify-payment',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRazorpayWebhookRoute =
  ApiPublicRazorpayWebhookRouteImport.update({
    id: '/api/public/razorpay-webhook',
    path: '/api/public/razorpay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSmartIndexSiteRoute = ApiPublicSmartIndexSiteRouteImport.update({
  id: '/api/public/smart-index-site',
  path: '/api/public/smart-index-site',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTrackAnalyticsRoute = ApiPublicTrackAnalyticsRouteImport.update({
  id: '/api/public/track-analytics',
  path: '/api/public/track-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTrackUrlClickRoute = ApiPublicTrackUrlClickRouteImport.update({
  id: '/api/public/track-url-click',
  path: '/api/public/track-url-click',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTranscribeAudioRoute =
  ApiPublicTranscribeAudioRouteImport.update({
    id: '/api/public/transcribe-audio',
    path: '/api/public/transcribe-audio',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWorkspaceAiChatRoute =
  ApiPublicWorkspaceAiChatRouteImport.update({
    id: '/api/public/workspace-ai-chat',
    path: '/api/public/workspace-ai-chat',
    getParentRoute: () => rootRouteImport,
  } as any)
const HeenaAdminIndexRoute = HeenaAdminIndexRouteImport.update({
  id: '/heena/admin/',
  path: '/heena/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const HeenaAdminSplatRoute = HeenaAdminSplatRouteImport.update({
  id: '/heena/admin/$',
  path: '/heena/admin/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFileSplatRoute = ApiPublicFileSplatRouteImport.update({
  id: '/api/public/file/$',
  path: '/api/public/file/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$code': typeof CodeRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/fund-rahul': typeof FundRahulRoute
  '/site-map': typeof SiteMapRoute
  '/legal/cancellation-policy': typeof LegalCancellationPolicyRoute
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/refund-policy': typeof LegalRefundPolicyRoute
  '/legal/terms-and-conditions': typeof LegalTermsAndConditionsRoute
  '/portfolio/$category': typeof PortfolioCategoryRoute
  '/pov/$category': typeof PovCategoryRoute
  '/referrals/$category': typeof ReferralsCategoryRoute
  '/heena/': typeof HeenaIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/pov/': typeof PovIndexRoute
  '/referrals/': typeof ReferralsIndexRoute
  '/api/public/analytics-insights': typeof ApiPublicAnalyticsInsightsRoute
  '/api/public/index-site-content': typeof ApiPublicIndexSiteContentRoute
  '/api/public/log-auth-event': typeof ApiPublicLogAuthEventRoute
  '/api/public/ramogu-chat': typeof ApiPublicRamoguChatRoute
  '/api/public/razorpay-create-order': typeof ApiPublicRazorpayCreateOrderRoute
  '/api/public/razorpay-verify-payment': typeof ApiPublicRazorpayVerifyPaymentRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/api/public/smart-index-site': typeof ApiPublicSmartIndexSiteRoute
  '/api/public/track-analytics': typeof ApiPublicTrackAnalyticsRoute
  '/api/public/track-url-click': typeof ApiPublicTrackUrlClickRoute
  '/api/public/transcribe-audio': typeof ApiPublicTranscribeAudioRoute
  '/api/public/workspace-ai-chat': typeof ApiPublicWorkspaceAiChatRoute
  '/heena/admin/$': typeof HeenaAdminSplatRoute
  '/heena/admin/': typeof HeenaAdminIndexRoute
  '/api/public/file/$': typeof ApiPublicFileSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$code': typeof CodeRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/fund-rahul': typeof FundRahulRoute
  '/site-map': typeof SiteMapRoute
  '/legal/cancellation-policy': typeof LegalCancellationPolicyRoute
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/refund-policy': typeof LegalRefundPolicyRoute
  '/legal/terms-and-conditions': typeof LegalTermsAndConditionsRoute
  '/portfolio/$category': typeof PortfolioCategoryRoute
  '/pov/$category': typeof PovCategoryRoute
  '/referrals/$category': typeof ReferralsCategoryRoute
  '/heena': typeof HeenaIndexRoute
  '/portfolio': typeof PortfolioIndexRoute
  '/pov': typeof PovIndexRoute
  '/referrals': typeof ReferralsIndexRoute
  '/api/public/analytics-insights': typeof ApiPublicAnalyticsInsightsRoute
  '/api/public/index-site-content': typeof ApiPublicIndexSiteContentRoute
  '/api/public/log-auth-event': typeof ApiPublicLogAuthEventRoute
  '/api/public/ramogu-chat': typeof ApiPublicRamoguChatRoute
  '/api/public/razorpay-create-order': typeof ApiPublicRazorpayCreateOrderRoute
  '/api/public/razorpay-verify-payment': typeof ApiPublicRazorpayVerifyPaymentRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/api/public/smart-index-site': typeof ApiPublicSmartIndexSiteRoute
  '/api/public/track-analytics': typeof ApiPublicTrackAnalyticsRoute
  '/api/public/track-url-click': typeof ApiPublicTrackUrlClickRoute
  '/api/public/transcribe-audio': typeof ApiPublicTranscribeAudioRoute
  '/api/public/workspace-ai-chat': typeof ApiPublicWorkspaceAiChatRoute
  '/heena/admin/$': typeof HeenaAdminSplatRoute
  '/heena/admin': typeof HeenaAdminIndexRoute
  '/api/public/file/$': typeof ApiPublicFileSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$code': typeof CodeRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/fund-rahul': typeof FundRahulRoute
  '/site-map': typeof SiteMapRoute
  '/legal/cancellation-policy': typeof LegalCancellationPolicyRoute
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/refund-policy': typeof LegalRefundPolicyRoute
  '/legal/terms-and-conditions': typeof LegalTermsAndConditionsRoute
  '/portfolio/$category': typeof PortfolioCategoryRoute
  '/pov/$category': typeof PovCategoryRoute
  '/referrals/$category': typeof ReferralsCategoryRoute
  '/heena/': typeof HeenaIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/pov/': typeof PovIndexRoute
  '/referrals/': typeof ReferralsIndexRoute
  '/api/public/analytics-insights': typeof ApiPublicAnalyticsInsightsRoute
  '/api/public/index-site-content': typeof ApiPublicIndexSiteContentRoute
  '/api/public/log-auth-event': typeof ApiPublicLogAuthEventRoute
  '/api/public/ramogu-chat': typeof ApiPublicRamoguChatRoute
  '/api/public/razorpay-create-order': typeof ApiPublicRazorpayCreateOrderRoute
  '/api/public/razorpay-verify-payment': typeof ApiPublicRazorpayVerifyPaymentRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/api/public/smart-index-site': typeof ApiPublicSmartIndexSiteRoute
  '/api/public/track-analytics': typeof ApiPublicTrackAnalyticsRoute
  '/api/public/track-url-click': typeof ApiPublicTrackUrlClickRoute
  '/api/public/transcribe-audio': typeof ApiPublicTranscribeAudioRoute
  '/api/public/workspace-ai-chat': typeof ApiPublicWorkspaceAiChatRoute
  '/heena/admin/$': typeof HeenaAdminSplatRoute
  '/heena/admin/': typeof HeenaAdminIndexRoute
  '/api/public/file/$': typeof ApiPublicFileSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$code'
    | '/about'
    | '/contact'
    | '/fund-rahul'
    | '/site-map'
    | '/legal/cancellation-policy'
    | '/legal/disclaimer'
    | '/legal/privacy-policy'
    | '/legal/refund-policy'
    | '/legal/terms-and-conditions'
    | '/portfolio/$category'
    | '/pov/$category'
    | '/referrals/$category'
    | '/heena/'
    | '/portfolio/'
    | '/pov/'
    | '/referrals/'
    | '/api/public/analytics-insights'
    | '/api/public/index-site-content'
    | '/api/public/log-auth-event'
    | '/api/public/ramogu-chat'
    | '/api/public/razorpay-create-order'
    | '/api/public/razorpay-verify-payment'
    | '/api/public/razorpay-webhook'
    | '/api/public/smart-index-site'
    | '/api/public/track-analytics'
    | '/api/public/track-url-click'
    | '/api/public/transcribe-audio'
    | '/api/public/workspace-ai-chat'
    | '/heena/admin/$'
    | '/heena/admin/'
    | '/api/public/file/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$code'
    | '/about'
    | '/contact'
    | '/fund-rahul'
    | '/site-map'
    | '/legal/cancellation-policy'
    | '/legal/disclaimer'
    | '/legal/privacy-policy'
    | '/legal/refund-policy'
    | '/legal/terms-and-conditions'
    | '/portfolio/$category'
    | '/pov/$category'
    | '/referrals/$category'
    | '/heena'
    | '/portfolio'
    | '/pov'
    | '/referrals'
    | '/api/public/analytics-insights'
    | '/api/public/index-site-content'
    | '/api/public/log-auth-event'
    | '/api/public/ramogu-chat'
    | '/api/public/razorpay-create-order'
    | '/api/public/razorpay-verify-payment'
    | '/api/public/razorpay-webhook'
    | '/api/public/smart-index-site'
    | '/api/public/track-analytics'
    | '/api/public/track-url-click'
    | '/api/public/transcribe-audio'
    | '/api/public/workspace-ai-chat'
    | '/heena/admin/$'
    | '/heena/admin'
    | '/api/public/file/$'
  id:
    | '__root__'
    | '/'
    | '/$code'
    | '/about'
    | '/contact'
    | '/fund-rahul'
    | '/site-map'
    | '/legal/cancellation-policy'
    | '/legal/disclaimer'
    | '/legal/privacy-policy'
    | '/legal/refund-policy'
    | '/legal/terms-and-conditions'
    | '/portfolio/$category'
    | '/pov/$category'
    | '/referrals/$category'
    | '/heena/'
    | '/portfolio/'
    | '/pov/'
    | '/referrals/'
    | '/api/public/analytics-insights'
    | '/api/public/index-site-content'
    | '/api/public/log-auth-event'
    | '/api/public/ramogu-chat'
    | '/api/public/razorpay-create-order'
    | '/api/public/razorpay-verify-payment'
    | '/api/public/razorpay-webhook'
    | '/api/public/smart-index-site'
    | '/api/public/track-analytics'
    | '/api/public/track-url-click'
    | '/api/public/transcribe-audio'
    | '/api/public/workspace-ai-chat'
    | '/heena/admin/$'
    | '/heena/admin/'
    | '/api/public/file/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CodeRoute: typeof CodeRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FundRahulRoute: typeof FundRahulRoute
  SiteMapRoute: typeof SiteMapRoute
  LegalCancellationPolicyRoute: typeof LegalCancellationPolicyRoute
  LegalDisclaimerRoute: typeof LegalDisclaimerRoute
  LegalPrivacyPolicyRoute: typeof LegalPrivacyPolicyRoute
  LegalRefundPolicyRoute: typeof LegalRefundPolicyRoute
  LegalTermsAndConditionsRoute: typeof LegalTermsAndConditionsRoute
  PortfolioCategoryRoute: typeof PortfolioCategoryRoute
  PovCategoryRoute: typeof PovCategoryRoute
  ReferralsCategoryRoute: typeof ReferralsCategoryRoute
  HeenaIndexRoute: typeof HeenaIndexRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
  PovIndexRoute: typeof PovIndexRoute
  ReferralsIndexRoute: typeof ReferralsIndexRoute
  ApiPublicAnalyticsInsightsRoute: typeof ApiPublicAnalyticsInsightsRoute
  ApiPublicIndexSiteContentRoute: typeof ApiPublicIndexSiteContentRoute
  ApiPublicLogAuthEventRoute: typeof ApiPublicLogAuthEventRoute
  ApiPublicRamoguChatRoute: typeof ApiPublicRamoguChatRoute
  ApiPublicRazorpayCreateOrderRoute: typeof ApiPublicRazorpayCreateOrderRoute
  ApiPublicRazorpayVerifyPaymentRoute: typeof ApiPublicRazorpayVerifyPaymentRoute
  ApiPublicRazorpayWebhookRoute: typeof ApiPublicRazorpayWebhookRoute
  ApiPublicSmartIndexSiteRoute: typeof ApiPublicSmartIndexSiteRoute
  ApiPublicTrackAnalyticsRoute: typeof ApiPublicTrackAnalyticsRoute
  ApiPublicTrackUrlClickRoute: typeof ApiPublicTrackUrlClickRoute
  ApiPublicTranscribeAudioRoute: typeof ApiPublicTranscribeAudioRoute
  ApiPublicWorkspaceAiChatRoute: typeof ApiPublicWorkspaceAiChatRoute
  HeenaAdminSplatRoute: typeof HeenaAdminSplatRoute
  HeenaAdminIndexRoute: typeof HeenaAdminIndexRoute
  ApiPublicFileSplatRoute: typeof ApiPublicFileSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$code': {
      id: '/$code'
      path: '/$code'
      fullPath: '/$code'
      preLoaderRoute: typeof CodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fund-rahul': {
      id: '/fund-rahul'
      path: '/fund-rahul'
      fullPath: '/fund-rahul'
      preLoaderRoute: typeof FundRahulRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site-map': {
      id: '/site-map'
      path: '/site-map'
      fullPath: '/site-map'
      preLoaderRoute: typeof SiteMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heena/': {
      id: '/heena/'
      path: '/heena'
      fullPath: '/heena/'
      preLoaderRoute: typeof HeenaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cancellation-policy': {
      id: '/legal/cancellation-policy'
      path: '/legal/cancellation-policy'
      fullPath: '/legal/cancellation-policy'
      preLoaderRoute: typeof LegalCancellationPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/disclaimer': {
      id: '/legal/disclaimer'
      path: '/legal/disclaimer'
      fullPath: '/legal/disclaimer'
      preLoaderRoute: typeof LegalDisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy-policy': {
      id: '/legal/privacy-policy'
      path: '/legal/privacy-policy'
      fullPath: '/legal/privacy-policy'
      preLoaderRoute: typeof LegalPrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/refund-policy': {
      id: '/legal/refund-policy'
      path: '/legal/refund-policy'
      fullPath: '/legal/refund-policy'
      preLoaderRoute: typeof LegalRefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms-and-conditions': {
      id: '/legal/terms-and-conditions'
      path: '/legal/terms-and-conditions'
      fullPath: '/legal/terms-and-conditions'
      preLoaderRoute: typeof LegalTermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$category': {
      id: '/portfolio/$category'
      path: '/portfolio/$category'
      fullPath: '/portfolio/$category'
      preLoaderRoute: typeof PortfolioCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pov/': {
      id: '/pov/'
      path: '/pov'
      fullPath: '/pov/'
      preLoaderRoute: typeof PovIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pov/$category': {
      id: '/pov/$category'
      path: '/pov/$category'
      fullPath: '/pov/$category'
      preLoaderRoute: typeof PovCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals/': {
      id: '/referrals/'
      path: '/referrals'
      fullPath: '/referrals/'
      preLoaderRoute: typeof ReferralsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals/$category': {
      id: '/referrals/$category'
      path: '/referrals/$category'
      fullPath: '/referrals/$category'
      preLoaderRoute: typeof ReferralsCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/analytics-insights': {
      id: '/api/public/analytics-insights'
      path: '/api/public/analytics-insights'
      fullPath: '/api/public/analytics-insights'
      preLoaderRoute: typeof ApiPublicAnalyticsInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/index-site-content': {
      id: '/api/public/index-site-content'
      path: '/api/public/index-site-content'
      fullPath: '/api/public/index-site-content'
      preLoaderRoute: typeof ApiPublicIndexSiteContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/log-auth-event': {
      id: '/api/public/log-auth-event'
      path: '/api/public/log-auth-event'
      fullPath: '/api/public/log-auth-event'
      preLoaderRoute: typeof ApiPublicLogAuthEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ramogu-chat': {
      id: '/api/public/ramogu-chat'
      path: '/api/public/ramogu-chat'
      fullPath: '/api/public/ramogu-chat'
      preLoaderRoute: typeof ApiPublicRamoguChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/razorpay-create-order': {
      id: '/api/public/razorpay-create-order'
      path: '/api/public/razorpay-create-order'
      fullPath: '/api/public/razorpay-create-order'
      preLoaderRoute: typeof ApiPublicRazorpayCreateOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/razorpay-verify-payment': {
      id: '/api/public/razorpay-verify-payment'
      path: '/api/public/razorpay-verify-payment'
      fullPath: '/api/public/razorpay-verify-payment'
      preLoaderRoute: typeof ApiPublicRazorpayVerifyPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/razorpay-webhook': {
      id: '/api/public/razorpay-webhook'
      path: '/api/public/razorpay-webhook'
      fullPath: '/api/public/razorpay-webhook'
      preLoaderRoute: typeof ApiPublicRazorpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/smart-index-site': {
      id: '/api/public/smart-index-site'
      path: '/api/public/smart-index-site'
      fullPath: '/api/public/smart-index-site'
      preLoaderRoute: typeof ApiPublicSmartIndexSiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track-analytics': {
      id: '/api/public/track-analytics'
      path: '/api/public/track-analytics'
      fullPath: '/api/public/track-analytics'
      preLoaderRoute: typeof ApiPublicTrackAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track-url-click': {
      id: '/api/public/track-url-click'
      path: '/api/public/track-url-click'
      fullPath: '/api/public/track-url-click'
      preLoaderRoute: typeof ApiPublicTrackUrlClickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/transcribe-audio': {
      id: '/api/public/transcribe-audio'
      path: '/api/public/transcribe-audio'
      fullPath: '/api/public/transcribe-audio'
      preLoaderRoute: typeof ApiPublicTranscribeAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/workspace-ai-chat': {
      id: '/api/public/workspace-ai-chat'
      path: '/api/public/workspace-ai-chat'
      fullPath: '/api/public/workspace-ai-chat'
      preLoaderRoute: typeof ApiPublicWorkspaceAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heena/admin/': {
      id: '/heena/admin/'
      path: '/heena/admin'
      fullPath: '/heena/admin/'
      preLoaderRoute: typeof HeenaAdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heena/admin/$': {
      id: '/heena/admin/$'
      path: '/heena/admin/$'
      fullPath: '/heena/admin/$'
      preLoaderRoute: typeof HeenaAdminSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/file/$': {
      id: '/api/public/file/$'
      path: '/api/public/file/$'
      fullPath: '/api/public/file/$'
      preLoaderRoute: typeof ApiPublicFileSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CodeRoute: CodeRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FundRahulRoute: FundRahulRoute,
  SiteMapRoute: SiteMapRoute,
  LegalCancellationPolicyRoute: LegalCancellationPolicyRoute,
  LegalDisclaimerRoute: LegalDisclaimerRoute,
  LegalPrivacyPolicyRoute: LegalPrivacyPolicyRoute,
  LegalRefundPolicyRoute: LegalRefundPolicyRoute,
  LegalTermsAndConditionsRoute: LegalTermsAndConditionsRoute,
  PortfolioCategoryRoute: PortfolioCategoryRoute,
  PovCategoryRoute: PovCategoryRoute,
  ReferralsCategoryRoute: ReferralsCategoryRoute,
  HeenaIndexRoute: HeenaIndexRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
  PovIndexRoute: PovIndexRoute,
  ReferralsIndexRoute: ReferralsIndexRoute,
  ApiPublicAnalyticsInsightsRoute: ApiPublicAnalyticsInsightsRoute,
  ApiPublicIndexSiteContentRoute: ApiPublicIndexSiteContentRoute,
  ApiPublicLogAuthEventRoute: ApiPublicLogAuthEventRoute,
  ApiPublicRamoguChatRoute: ApiPublicRamoguChatRoute,
  ApiPublicRazorpayCreateOrderRoute: ApiPublicRazorpayCreateOrderRoute,
  ApiPublicRazorpayVerifyPaymentRoute: ApiPublicRazorpayVerifyPaymentRoute,
  ApiPublicRazorpayWebhookRoute: ApiPublicRazorpayWebhookRoute,
  ApiPublicSmartIndexSiteRoute: ApiPublicSmartIndexSiteRoute,
  ApiPublicTrackAnalyticsRoute: ApiPublicTrackAnalyticsRoute,
  ApiPublicTrackUrlClickRoute: ApiPublicTrackUrlClickRoute,
  ApiPublicTranscribeAudioRoute: ApiPublicTranscribeAudioRoute,
  ApiPublicWorkspaceAiChatRoute: ApiPublicWorkspaceAiChatRoute,
  HeenaAdminSplatRoute: HeenaAdminSplatRoute,
  HeenaAdminIndexRoute: HeenaAdminIndexRoute,
  ApiPublicFileSplatRoute: ApiPublicFileSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
